In [95]:
import numpy as np

In [96]:
root_size = 8

x = np.arange(root_size ** 2).reshape((root_size,-1))
diag_mask = np.identity(root_size, dtype=bool)

In [97]:
x[diag_mask] = 0

In [100]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  0, 10, 11, 12, 13, 14, 15],
       [16, 17,  0, 19, 20, 21, 22, 23],
       [24, 25, 26,  0, 28, 29, 30, 31],
       [32, 33, 34, 35,  0, 37, 38, 39],
       [40, 41, 42, 43, 44,  0, 46, 47],
       [48, 49, 50, 51, 52, 53,  0, 55],
       [56, 57, 58, 59, 60, 61, 62,  0]])

In [99]:
# take a vertical slice
slices = 3
slices_rows = 3

for slice in range(slices):
    base = slice * slices_rows 
    top = base + slices_rows 

    lhs_box_base = (slice - 1)* slices_rows
    lhs_box_top = lhs_box_base + slices_rows 

    chunk_D = x[base : top]
    print(chunk_D)
    # print(chunk_D[bl_mask])
    # print(chunk_D.shape[0])

    lhs_box = chunk_D.T[0 : lhs_box_top].T
    rhs_box = chunk_D.T[lhs_box_top:].T
    bl_mask = ~np.triu(np.ones_like(rhs_box, dtype=bool))

    tri = rhs_box[bl_mask]
    print(lhs_box)
    print(tri)

[[ 0  1  2  3  4  5  6  7]
 [ 8  0 10 11 12 13 14 15]
 [16 17  0 19 20 21 22 23]]
[]
[ 8 16 17]
[[24 25 26  0 28 29 30 31]
 [32 33 34 35  0 37 38 39]
 [40 41 42 43 44  0 46 47]]
[[24 25 26]
 [32 33 34]
 [40 41 42]]
[35 43 44]
[[48 49 50 51 52 53  0 55]
 [56 57 58 59 60 61 62  0]]
[[48 49 50 51 52 53]
 [56 57 58 59 60 61]]
[62]
